.\" Manpage for ocelotgui.
.TH man 1 "1.8.0" "ocelotgui man page"
.SH NAME
ocelotgui \- GUI client for MySQL or MariaDB
.SH SYNOPSIS
ocelotgui [options]
.SH DESCRIPTION
The ocelotgui GUI, a database client, allows users to connect to a MySQL or MariaDB DBMS server, enter SQL statements, and receive results. Some of its features are: syntax highlighting, user-settable colors and fonts for each part of the screen, result-set displays with multi-line rows and resizable columns, and a debugger.
.SH OPTIONS
See http://github.com/ocelot-inc/ocelotgui or start ocelotgui and pick menu option Help|Manual
.SH BUGS
See https://github.com/ocelot-inc/ocelotgui/issues
.SH AUTHOR
Peter Gulutzan (first-initial surname at-sign ocelot.ca)
.SH COPYRIGHT
Copyright (c) 2022 by Peter Gulutzan.
