.\" Manpage for pgoptionfiles.
.TH man 1 "1.0.0" "pgoptionfiles man page"
.SH NAME
pgoptionfiles \- show what option files MySQL or MariaDB reads
.SH SYNOPSIS
pgoptionfiles [options]
.SH DESCRIPTION
Show what option files a MySQL or MariaDB Connector C library looks for, on Linux.
.SH OPTIONS
See http://github.com/pgulutzan/pgoptionfiles
.SH BUGS
See https://github.com/pgulutzan/pgoptionfiles/issues
.SH AUTHOR
Peter Gulutzan (first-initial surname at-sign ocelot.ca)
.SH COPYRIGHT
Copyright (c) 2025 by Peter Gulutzan.
